<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spandelete-button-I3VYV9IR48FE2Y</name>
   <tag></tag>
   <elementGuidId>b40445da-828b-44b4-adb5-2645aa7f931e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='delete-button-I3VYV9IR48FE2Y']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delete-button-I3VYV9IR48FE2Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a29f7277-98ac-4177-a2c8-a001fb25a0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete-button-I3VYV9IR48FE2Y</value>
      <webElementGuid>73c5a4b7-bb40-4606-96e9-87941122cb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-base a-button-small</value>
      <webElementGuid>1a6cbd35-fd93-40ba-ad81-abaf09326181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-button-I3VYV9IR48FE2Y&quot;)</value>
      <webElementGuid>31e0aef9-e757-4364-be12-aca320e6f779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='delete-button-I3VYV9IR48FE2Y']</value>
      <webElementGuid>fb19f308-1d4a-4b19-946f-28d78c1ccbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemAction_I3VYV9IR48FE2Y']/div/div/div/div[3]/form/span/span</value>
      <webElementGuid>794c086a-bfa5-4bdb-9520-a8b5b72f5407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/span/span</value>
      <webElementGuid>c900601b-5f9a-463c-a42c-e26bab5b5e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'delete-button-I3VYV9IR48FE2Y']</value>
      <webElementGuid>d26ab1ec-69e3-4859-9657-d95ec5b39831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
